import styles from './gallery.module.css';

export const metadata = {
  title: '个人画廊网站',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: {
  children: React.ReactNode;
}) {
  // return (
  //   <html lang="en">
  //     <body className={styles.body}>{children}</body>
  //   </html>
  // )
  return <div className={styles.body}>{children}</div>;
}
