import styles from './gallery.module.css';

export const metadata = {
  title: '个人画廊网站',
  description: 'Generated by Next.js',
}

export default function Layout({ children }: {
  children: React.ReactNode;
}) {
  return <div className={styles.body}>{children}</div>;
}
